// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250923110357_TestData")]
    partial class TestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sodales, enim et facilisis commodo, est augue venenatis ligula, in convallis erat felis nec nisi. In eleifend ligula a nunc efficitur, ut finibus enim fringilla. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum sit amet massa vel justo condimentum luctus vel in lectus. Vivamus pellentesque, dolor vel pharetra mollis, erat ex fringilla est, at convallis erat nisl nec nisi. In eleifend ligula a nunc efficitur, ut finibus enim fringilla.",
                            ImageUrl = "/images/products/sb-ang1.png",
                            IsActive = true,
                            Name = "Angular Speedster Board 2000",
                            Price = 20000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sodales, enim et facilisis commodo, est augue venenatis ligula, in convallis erat felis nec nisi. In eleifend ligula a nunc efficitur, ut finibus enim fringilla. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum sit amet massa vel justo condimentum luctus vel in lectus. Vivamus pellentesque, dolor vel pharetra mollis, erat ex fringilla est, at convallis erat nisl nec nisi. In eleifend ligula a nunc efficitur, ut finibus enim fringilla.",
                            ImageUrl = "/images/products/sb-ang1.png",
                            IsActive = true,
                            Name = "Angular Speedster Board 2000",
                            Price = 20000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sodales, enim et facilisis commodo, est augue venenatis ligula, in convallis erat felis nec nisi. In eleifend ligula a nunc efficitur, ut finibus enim fringilla. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum sit amet massa vel justo condimentum luctus vel in lectus. Vivamus pellentesque, dolor vel pharetra mollis, erat ex fringilla est, at convallis erat nisl nec nisi. In eleifend ligula a nunc efficitur, ut finibus enim fringilla.",
                            ImageUrl = "/images/products/sb-ang1.png",
                            IsActive = true,
                            Name = "Angular Speedster Board 2000",
                            Price = 20000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sodales, enim et facilisis commodo, est augue venenatis ligula, in convallis erat felis nec nisi. In eleifend ligula a nunc efficitur, ut finibus enim fringilla. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum sit amet massa vel justo condimentum luctus vel in lectus. Vivamus pellentesque, dolor vel pharetra mollis, erat ex fringilla est, at convallis erat nisl nec nisi. In eleifend ligula a nunc efficitur, ut finibus enim fringilla.",
                            ImageUrl = "/images/products/sb-ang1.png",
                            IsActive = true,
                            Name = "Angular Speedster Board 2000",
                            Price = 20000m,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
