FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src/EmailWorker

# 1) Sadece worker'ın projelerini kopyala
COPY EmailWorker/EmailWorker.csproj ./
COPY Shared/Shared.csproj ../Shared/

# 2) Bağımlı projeyi (Shared) restore et
WORKDIR /src
RUN dotnet restore EmailWorker/EmailWorker.csproj

# 3) Sadece worker kodunu kopyala
COPY EmailWorker ./EmailWorker
COPY Shared ./Shared

# 4) Publish et
WORKDIR /src/EmailWorker
RUN dotnet publish -c Release -o /publish

# RUNTIME
FROM mcr.microsoft.com/dotnet/runtime:9.0
WORKDIR /worker
COPY --from=build /publish .

ENTRYPOINT ["dotnet", "EmailWorker.dll"]
