FROM node:18-alpine AS build

WORKDIR /app

# Sadece client klasörünün package.json'ını al
COPY package*.json ./

RUN npm install

# ŞİMDİ sadece client klasörünü kopyala, tüm projeyi değil
COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
